import { NextRequest, NextResponse } from "next/server";
import { resolveStoreContext } from "@/theme-engine/store-context/resolve-store";
import { getStoreDb } from "@/data/db/store-db.server";
import { getSeoUrlMode } from "@/data/store/settings";
import { buildCategoryHref, buildProductHref } from "@/lib/seo/build-store-href";

export const dynamic = "force-dynamic";
const s=(v:unknown)=>String(v??"").trim();
const obj=(v:any)=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
const positiveNo=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)&&n>0?Math.floor(n):0};
const entityIds=(v:any)=>Array.isArray(v)?v.map((x:any)=>s(x?.id||x)).filter(Boolean):[];
function money(value:unknown,currency="SAR"){const n=Number(value??0);try{return new Intl.NumberFormat("ar-SA",{style:"currency",currency,maximumFractionDigits:2}).format(n)}catch{return `${n.toFixed(2)} ر.س`}}
function normalizePageSlug(value:unknown){let raw=s(value);if(!raw)return"";try{raw=decodeURIComponent(raw)}catch{}return raw.toLowerCase().replace(/^\s+|\s+$/g,"").replace(/^\/+/,"").replace(/^p\/+/i,"").replace(/^pages\/+/i,"").replace(/[\\?#%]+/g,"").replace(/\s+/g,"-").replace(/\/+/g,"-").replace(/-+/g,"-").replace(/^-+|-+$/g,"")}
function matchScore(row:any,pageType:string,referenceId:string|null){const scope=obj(row.page_scope),targets=Array.isArray(scope.targets)?scope.targets:[];if(referenceId&&targets.some((i:any)=>s(i?.type)===pageType&&s(i?.id)===referenceId))return 1000;if(pageType==="home"&&scope.home)return 500;if(pageType==="product"&&scope.allProducts)return 400;if(pageType==="category"&&scope.allCategories)return 400;if(scope.pageType==="all")return 100;if(scope.pageType===pageType&&(!scope.referenceId||s(scope.referenceId)===referenceId))return scope.referenceId?900:300;return-1}
async function resolveButtonUrl({db,storeId,content}:{db:any;storeId:string;content:Record<string,any>}){const type=s(content.buttonLinkType||"none"),value=s(content.buttonLinkValue),existing=s(content.buttonUrl);if(type==="external"||type==="internal")return existing||value;if(!value)return existing;if(type==="product"){const[{data:row},mode]=await Promise.all([db.from("products").select("id,name,public_no,metadata").eq("store_id",storeId).eq("id",value).maybeSingle(),getSeoUrlMode(storeId)]);if(!row)return"";const m=obj(row.metadata),slug=s(m.seo_slug)||s(row.name)||"product";return buildProductHref({mode,slugNameAr:slug,slugNameEn:slug,publicNo:positiveNo(row.public_no),shortCode:s(m.short_url||m.shortUrl||m.short_code||m.shortCode)||null})}if(type==="category"){const[{data:row},mode]=await Promise.all([db.from("categories").select("id,name,slug,public_no").eq("store_id",storeId).eq("id",value).maybeSingle(),getSeoUrlMode(storeId)]);if(!row)return"";const slug=s(row.slug)||s(row.name)||"category";return buildCategoryHref({mode,slugNameAr:slug,slugNameEn:slug,publicNo:positiveNo(row.public_no),shortCode:null})}if(type==="page"){const{data:row}=await db.from("store_pages").select("id,title,seo_slug,is_active").eq("store_id",storeId).eq("id",value).eq("is_active",true).maybeSingle();if(!row)return"";const slug=normalizePageSlug(row.seo_slug)||normalizePageSlug(row.title)||normalizePageSlug(row.id);return slug?`/p/${encodeURIComponent(slug)}`:""}return existing}

async function loadProducts(db:any,storeId:string,popupType:string,typeData:Record<string,any>,referenceId:string|null){let ids:string[]=[];
 if(popupType==="product_recommendation")ids=entityIds(typeData.products);
 if(popupType==="discount")ids=entityIds(typeData.products);
 if(popupType==="upsell")ids=[...entityIds(typeData.baseProduct),...entityIds(typeData.upgradeProduct)];
 if(popupType==="cross_sell")ids=[...entityIds(typeData.baseProduct),...entityIds(typeData.complements)];
 if(popupType==="social_proof"||popupType==="low_stock"||popupType==="new_arrival")ids=entityIds(typeData.products);
 if(!ids.length&&["product_recommendation","new_arrival"].includes(popupType)){let q=db.from("products").select("id,name,public_no,metadata,created_at").eq("store_id",storeId).eq("status","sale").order("created_at",{ascending:false}).limit(Math.min(12,Number(typeData.maxProducts||typeData.count||4)));const{data}=await q;ids=(data||[]).map((x:any)=>x.id)}
 if(!ids.length&&referenceId&&["low_stock","social_proof"].includes(popupType))ids=[referenceId];
 ids=[...new Set(ids)].slice(0,12);if(!ids.length)return[];
 const[{data:rows},mode]=await Promise.all([db.from("products").select("id,name,public_no,metadata,product_pricing(price,sale_price,currency),product_stock(quantity,unlimited_quantity),product_media(original_url,thumbnail_url,is_default,sort_order),product_options(id)").eq("store_id",storeId).in("id",ids),getSeoUrlMode(storeId)]);
 return (rows||[]).sort((a:any,b:any)=>ids.indexOf(a.id)-ids.indexOf(b.id)).map((row:any)=>{const m=obj(row.metadata),pricing=Array.isArray(row.product_pricing)?row.product_pricing[0]:row.product_pricing||{},stock=Array.isArray(row.product_stock)?row.product_stock[0]:row.product_stock||{},media=(Array.isArray(row.product_media)?row.product_media:[]).sort((a:any,b:any)=>Number(b.is_default)-Number(a.is_default)||Number(a.sort_order)-Number(b.sort_order))[0]||{},price=Number(pricing.sale_price||pricing.price||0),compare=Number(pricing.sale_price)>0&&Number(pricing.price)>Number(pricing.sale_price)?Number(pricing.price):null,currency=s(pricing.currency)||"SAR",slug=s(m.seo_slug)||s(row.name)||"product";return{id:row.id,name:row.name,href:buildProductHref({mode,slugNameAr:slug,slugNameEn:slug,publicNo:positiveNo(row.public_no),shortCode:s(m.short_url||m.shortUrl||m.short_code||m.shortCode)||null}),imageUrl:s(media.thumbnail_url||media.original_url),price,comparePrice:compare,priceLabel:money(price,currency),comparePriceLabel:compare?money(compare,currency):"",rating:Number(m.rating_avg||m.rating||0)||null,stock:stock.unlimited_quantity?null:Number(stock.quantity??0),hasOptions:Array.isArray(row.product_options)&&row.product_options.length>0}})}

async function loadLoyalty(db:any,storeId:string){try{const{data:rewards}=await db.from("store_loyalty_rewards").select("id,name,points_cost").eq("store_id",storeId).eq("is_active",true).order("sort_order").limit(3);return{points:0,rewards:(rewards||[]).map((r:any)=>({id:r.id,name:r.name,pointsCost:Number(r.points_cost||0)}))}}catch{return null}}

export async function GET(request:NextRequest){try{const context=await resolveStoreContext(),storeId=context.store?.id;if(!storeId)return NextResponse.json({data:null});const pageType=s(request.nextUrl.searchParams.get("pageType")||"other"),referenceId=s(request.nextUrl.searchParams.get("referenceId"))||null,device=s(request.nextUrl.searchParams.get("device")||"desktop"),now=new Date().toISOString(),db:any=await getStoreDb(storeId);const{data,error}=await db.from("marketing_popups").select("id,name,popup_type,status,priority,starts_at,ends_at,trigger_type,page_scope,content,design,device_scope,updated_at").eq("store_id",storeId).in("status",["active","scheduled"]).order("priority",{ascending:true}).limit(100);if(error)throw error;const candidates=(data||[]).filter((r:any)=>{const ds=s(r.device_scope||"both");if(!(ds==="both"||ds===device))return false;if(r.starts_at&&String(r.starts_at)>now)return false;if(r.ends_at&&String(r.ends_at)<now)return false;return matchScore(r,pageType,referenceId)>=0}).sort((a:any,b:any)=>matchScore(b,pageType,referenceId)-matchScore(a,pageType,referenceId)||Number(a.priority??100)-Number(b.priority??100));const row=candidates[0];if(!row)return NextResponse.json({data:null});const content=obj(row.content),typeData=obj(content.typeData);const[buttonUrl,products,loyalty]=await Promise.all([resolveButtonUrl({db,storeId,content}),loadProducts(db,storeId,s(row.popup_type),typeData,referenceId),row.popup_type==="loyalty"?loadLoyalty(db,storeId):Promise.resolve(null)]);let mediaUrl=s(content.mediaUrl);if(content.mediaType==="video"&&!mediaUrl&&s(content.mediaMuxPlaybackId))mediaUrl=`https://stream.mux.com/${s(content.mediaMuxPlaybackId)}.m3u8`;return NextResponse.json({data:{id:row.id,name:row.name,popupType:row.popup_type,priority:row.priority,startsAt:row.starts_at,endsAt:row.ends_at,triggerType:row.trigger_type,pageScope:row.page_scope||{},content:{...content,mediaUrl,buttonUrl},design:row.design||{},deviceScope:row.device_scope,products,loyalty,socialProof:null}})}catch(error:any){console.error("[marketing-popups] GET failed",error);return NextResponse.json({data:null},{status:200})}}
